version: "3"
services:
    app:
        build: .
        ports:
            - "8000:4200"
        volumes:
            # - "usr/src/app/node_modules"
            # - "./:/usr/share/nginx/html"
            - "/app/node_modules"
            - ".:/app"